analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.4319149
  brandStrength: 0
  lightness: 0.6964775
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  rhythmicContrast: 0.9740204
typography_spectrum: 0.3468085
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 1
favicon: null
name: vndre
